//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTicketingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_replacement
    {
        public int Id { get; set; }
        public decimal Quantity { get; set; }
        public string Remark { get; set; }
        public int IdComplainIssue { get; set; }
        public int IdPart { get; set; }
        public int IdPartStatus { get; set; }
    
        public virtual tbl_complain_issue tbl_complain_issue { get; set; }
        public virtual tbl_part tbl_part { get; set; }
        public virtual tbl_part_status tbl_part_status { get; set; }
    }
}
