//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTicketingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_complain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_complain()
        {
            this.tbl_complain_issue = new HashSet<tbl_complain_issue>();
        }
    
        public int Id { get; set; }
        public System.DateTime RequstedDate { get; set; }
        public string Status { get; set; }
        public string Aging { get; set; }
        public string Remark { get; set; }
        public int IdAccount { get; set; }
        public int IdTypeOfComplain { get; set; }
        public int IdCompanyBranch { get; set; }
    
        public virtual tbl_account tbl_account { get; set; }
        public virtual tbl_company_branch tbl_company_branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_complain_issue> tbl_complain_issue { get; set; }
        public virtual tbl_type_of_complain tbl_type_of_complain { get; set; }
    }
}
