//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTicketingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_assigned_service_engineer_to_issue
    {
        public int Id { get; set; }
        public int IdServiceEngineer { get; set; }
        public int IdIssue { get; set; }
        public string Remark { get; set; }
        public bool PreventedFromWorking { get; set; }
    
        public virtual tbl_complain_issue tbl_complain_issue { get; set; }
        public virtual tbl_service_engineer tbl_service_engineer { get; set; }
    }
}
