//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTicketingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_complain_issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_complain_issue()
        {
            this.tbl_additional_payment = new HashSet<tbl_additional_payment>();
            this.tbl_assigned_service_engineer_to_issue = new HashSet<tbl_assigned_service_engineer_to_issue>();
            this.tbl_repairment = new HashSet<tbl_repairment>();
            this.tbl_replacement = new HashSet<tbl_replacement>();
            this.tbl_vendor_payment = new HashSet<tbl_vendor_payment>();
        }
    
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateFixed { get; set; }
        public Nullable<bool> Replaced { get; set; }
        public string Remark { get; set; }
        public int IdComplain { get; set; }
        public int IdIssueStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_additional_payment> tbl_additional_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_assigned_service_engineer_to_issue> tbl_assigned_service_engineer_to_issue { get; set; }
        public virtual tbl_complain tbl_complain { get; set; }
        public virtual tbl_issue_status tbl_issue_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_repairment> tbl_repairment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_replacement> tbl_replacement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_vendor_payment> tbl_vendor_payment { get; set; }
    }
}
